services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${DB_USER} -d ${DB_NAME} -p ${DB_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: ./auth-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL_DOCKER: ${DB_URL_DOCKER}
      DB_URL_LOCAL: ${DB_URL_LOCAL}
    volumes:
      - ./auth-app:/docker-app
    working_dir: /docker-app

volumes:
  postgres_data: